spring.application.name=farmstep

spring.datasource.url=jdbc:postgresql://localhost:5432/farmstep
spring.datasource.username=postgres
spring.datasource.password=2450

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

openai.api.key=${OPENAI_API_KEY:}

spring.thymeleaf.cache=false

server.port=8080